"use client";

import React, { useState, useMemo } from "react";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Calendar, Clock, Sparkles } from "lucide-react";
import { BlogTagFilter, getArticleTags } from "@/components/blog/blog-tag-filter";

interface Article {
  slug: string;
  title: string;
  description: string;
  date: string;
  readingTime: string;
  gradient: string;
  icon: string;
  image?: string | null;
  isAutoGenerated?: boolean;
}

interface BlogArticleGridProps {
  autoPosts: Article[];
  allArticles: Article[];
}

export function BlogArticleGrid({ autoPosts, allArticles }: BlogArticleGridProps) {
  const [activeTags, setActiveTags] = useState<string[]>([]);

  // Build a tag map for all articles
  const articleTagMap = useMemo(() => {
    const map = new Map<string, string[]>();
    allArticles.forEach((article) => {
      map.set(article.slug, getArticleTags(article.title, article.description));
    });
    return map;
  }, [allArticles]);

  // Filter articles by active tags
  const filteredAutoPosts = useMemo(() => {
    if (activeTags.length === 0) return autoPosts;
    return autoPosts.filter((article) => {
      const articleTags = articleTagMap.get(article.slug) || [];
      return activeTags.some((tag) => articleTags.includes(tag));
    });
  }, [autoPosts, activeTags, articleTagMap]);

  const filteredStaticArticles = useMemo(() => {
    const staticArticles = allArticles.filter((a) => !a.isAutoGenerated);
    if (activeTags.length === 0) return staticArticles;
    return staticArticles.filter((article) => {
      const articleTags = articleTagMap.get(article.slug) || [];
      return activeTags.some((tag) => articleTags.includes(tag));
    });
  }, [allArticles, activeTags, articleTagMap]);

  const hasFilters = activeTags.length > 0;
  const totalFiltered = filteredAutoPosts.length + filteredStaticArticles.length;

  return (
    <>
      {/* Tag Filter */}
      <section className="px-4 sm:px-6 pb-6">
        <div className="mx-auto max-w-5xl">
          <BlogTagFilter onFilterChange={setActiveTags} />
          {hasFilters && (
            <p className="text-xs text-muted-foreground mt-3">
              Menampilkan {totalFiltered} artikel dengan filter aktif
            </p>
          )}
        </div>
      </section>

      {/* Auto-Generated Posts Section */}
      {filteredAutoPosts.length > 0 && (
        <section className="px-4 sm:px-6 pb-8">
          <div className="mx-auto max-w-5xl">
            <div className="flex items-center gap-2 mb-5">
              <Sparkles className="h-5 w-5 text-[#10B981]" />
              <h2 className="text-lg font-bold text-foreground font-[family-name:var(--font-montserrat)]">
                Artikel Terbaru
              </h2>
              <span className="ml-1 px-2 py-0.5 rounded-full bg-[#10B981]/10 text-[10px] font-semibold text-[#10B981] border border-[#10B981]/20">
                BARU
              </span>
            </div>
            <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
              {filteredAutoPosts.map((article) => (
                <Link
                  key={article.slug}
                  href={`/blog/${article.slug}`}
                  className="group rounded-2xl overflow-hidden bg-card border border-[#10B981]/20 hover:border-[#10B981]/50 transition-all duration-200"
                >
                  <div
                    className={`h-32 sm:h-36 relative overflow-hidden ${!article.image ? `bg-gradient-to-br ${article.gradient}` : ""}`}
                  >
                    {article.image ? (
                      <>
                        <Image
                          src={article.image}
                          alt={article.title}
                          fill
                          className="object-cover"
                          sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw"
                        />
                        <div className="absolute inset-0 bg-gradient-to-t from-card/80 dark:from-[#111113]/80 via-transparent to-transparent" />
                      </>
                    ) : (
                      <>
                        <span className="text-4xl opacity-80">{article.icon}</span>
                        <div className="absolute inset-0 bg-gradient-to-t from-card/80 dark:from-[#111113]/80 to-transparent" />
                      </>
                    )}
                    <span className="absolute top-3 right-3 px-2 py-0.5 rounded-full bg-[#10B981] text-[9px] font-bold text-white z-10">
                      BARU
                    </span>
                  </div>

                  <div className="p-4">
                    <div className="flex items-center gap-3 text-[11px] text-muted-foreground mb-2">
                      <span className="flex items-center gap-1">
                        <Calendar className="h-3 w-3 text-[#10B981]" />
                        {article.date}
                      </span>
                      <span className="flex items-center gap-1">
                        <Clock className="h-3 w-3 text-[#10B981]" />
                        {article.readingTime}
                      </span>
                    </div>
                    <h2 className="font-bold text-foreground text-sm sm:text-base mb-2 group-hover:text-[#10B981] transition-colors line-clamp-2 font-[family-name:var(--font-montserrat)]">
                      {article.title}
                    </h2>
                    <p className="text-xs text-muted-foreground line-clamp-2 mb-3">
                      {article.description}
                    </p>
                    <span className="inline-flex items-center gap-1 text-xs font-medium text-[#10B981] group-hover:gap-2 transition-all">
                      Baca Selengkapnya
                      <ArrowRight className="h-3 w-3" />
                    </span>
                  </div>
                </Link>
              ))}
            </div>
          </div>
        </section>
      )}

      {/* All Articles Grid */}
      {filteredStaticArticles.length > 0 && (
        <section className="px-4 sm:px-6 pb-16">
          <div className="mx-auto max-w-5xl">
            <h2 className="text-lg font-bold text-foreground mb-5 font-[family-name:var(--font-montserrat)]">
              {hasFilters ? "Artikel yang Cocok" : "Semua Artikel"}
            </h2>
            <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
              {filteredStaticArticles.map((article) => (
                <Link
                  key={article.slug}
                  href={`/blog/${article.slug}`}
                  className="group rounded-2xl overflow-hidden bg-card border border-border hover:border-[#10B981]/30 transition-all duration-200"
                >
                  <div
                    className={`h-32 sm:h-36 relative overflow-hidden flex items-center justify-center bg-gradient-to-br ${article.gradient}`}
                  >
                    <span className="text-4xl opacity-80">{article.icon}</span>
                    <div className="absolute inset-0 bg-gradient-to-t from-card/80 dark:from-[#111113]/80 to-transparent" />
                  </div>

                  <div className="p-4">
                    <div className="flex items-center gap-3 text-[11px] text-muted-foreground mb-2">
                      <span className="flex items-center gap-1">
                        <Calendar className="h-3 w-3 text-[#10B981]" />
                        {article.date}
                      </span>
                      <span className="flex items-center gap-1">
                        <Clock className="h-3 w-3 text-[#10B981]" />
                        {article.readingTime}
                      </span>
                    </div>
                    <h2 className="font-bold text-foreground text-sm sm:text-base mb-2 group-hover:text-[#10B981] transition-colors line-clamp-2 font-[family-name:var(--font-montserrat)]">
                      {article.title}
                    </h2>
                    <p className="text-xs text-muted-foreground line-clamp-2 mb-3">
                      {article.description}
                    </p>
                    <span className="inline-flex items-center gap-1 text-xs font-medium text-[#10B981] group-hover:gap-2 transition-all">
                      Baca Selengkapnya
                      <ArrowRight className="h-3 w-3" />
                    </span>
                  </div>
                </Link>
              ))}
            </div>
          </div>
        </section>
      )}

      {/* No results */}
      {hasFilters && totalFiltered === 0 && (
        <section className="px-4 sm:px-6 pb-16">
          <div className="mx-auto max-w-5xl text-center py-12">
            <p className="text-muted-foreground text-sm">
              Tidak ada artikel yang cocok dengan filter. Coba hapus beberapa filter.
            </p>
          </div>
        </section>
      )}
    </>
  );
}
