"use client";

import { useState, useMemo } from "react";
import Image from "next/image";
import Link from "next/link";
import { Search, X, ArrowRight, Calendar, Clock } from "lucide-react";

interface Article {
  slug: string;
  title: string;
  description: string;
  date: string;
  readingTime: string;
  gradient: string;
  icon: string;
  image: string | null;
  isAutoGenerated: boolean;
}

interface BlogSearchClientProps {
  articles: Article[];
}

export function BlogSearchClient({ articles }: BlogSearchClientProps) {
  const [query, setQuery] = useState("");
  const [isFocused, setIsFocused] = useState(false);

  const results = useMemo(() => {
    if (!query.trim()) return [];
    const q = query.toLowerCase().trim();
    return articles.filter(
      (a) =>
        a.title.toLowerCase().includes(q) ||
        a.description.toLowerCase().includes(q)
    );
  }, [query, articles]);

  const isSearching = query.trim().length > 0;

  return (
    <div className="relative max-w-xl mx-auto">
      {/* Search Input */}
      <div className={`relative flex items-center rounded-xl border transition-all duration-200 ${isFocused ? "border-[#10B981] shadow-lg shadow-[#10B981]/10 bg-card" : "border-border bg-card/50"}`}>
        <Search className="h-4 w-4 text-muted-foreground ml-3.5 shrink-0" />
        <input
          type="text"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          onFocus={() => setIsFocused(true)}
          onBlur={() => setTimeout(() => setIsFocused(false), 200)}
          placeholder="Cari artikel... (misal: TikTok, Instagram, watermark)"
          className="flex-1 h-11 px-3 bg-transparent text-foreground text-sm placeholder:text-muted-foreground outline-none"
        />
        {query && (
          <button
            onClick={() => setQuery("")}
            className="mr-2 w-7 h-7 rounded-lg flex items-center justify-center text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
          >
            <X className="h-3.5 w-3.5" />
          </button>
        )}
      </div>

      {/* Search Results Dropdown */}
      {isSearching && isFocused && (
        <div className="absolute top-full left-0 right-0 mt-2 rounded-xl bg-card border border-border shadow-xl shadow-black/10 z-50 overflow-hidden max-h-[400px] overflow-y-auto">
          {results.length === 0 ? (
            <div className="p-6 text-center">
              <p className="text-sm text-muted-foreground">
                Tidak ada artikel yang cocok dengan &ldquo;{query}&rdquo;
              </p>
              <p className="text-xs text-muted-foreground/60 mt-1">
                Coba kata kunci lain seperti &ldquo;TikTok&rdquo; atau &ldquo;watermark&rdquo;
              </p>
            </div>
          ) : (
            <div className="p-2">
              <p className="px-3 py-1.5 text-[10px] font-semibold text-muted-foreground uppercase tracking-wider">
                {results.length} artikel ditemukan
              </p>
              {results.slice(0, 8).map((article) => (
                <Link
                  key={article.slug}
                  href={`/blog/${article.slug}`}
                  className="flex items-center gap-3 p-2.5 rounded-lg hover:bg-muted/50 transition-colors group"
                >
                  {/* Thumbnail */}
                  <div className={`w-12 h-12 rounded-lg shrink-0 overflow-hidden relative ${!article.image ? `bg-gradient-to-br ${article.gradient} flex items-center justify-center` : ""}`}>
                    {article.image ? (
                      <Image
                        src={article.image}
                        alt={article.title}
                        fill
                        className="object-cover"
                        sizes="48px"
                      />
                    ) : (
                      <span className="text-lg">{article.icon}</span>
                    )}
                  </div>
                  {/* Text */}
                  <div className="flex-1 min-w-0">
                    <h4 className="text-sm font-medium text-foreground group-hover:text-[#10B981] transition-colors line-clamp-1">
                      {article.title}
                    </h4>
                    <div className="flex items-center gap-2 text-[10px] text-muted-foreground mt-0.5">
                      <span>{article.date}</span>
                      <span className="flex items-center gap-0.5">
                        <Clock className="h-2.5 w-2.5" />
                        {article.readingTime}
                      </span>
                      {article.isAutoGenerated && (
                        <span className="px-1 py-0.5 rounded bg-[#10B981]/10 text-[#10B981] text-[8px] font-bold">
                          BARU
                        </span>
                      )}
                    </div>
                  </div>
                  <ArrowRight className="h-3.5 w-3.5 text-muted-foreground group-hover:text-[#10B981] shrink-0 transition-colors" />
                </Link>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
